server:
  port: 8086

spring:
  application:
    name: auth
  datasource:
    username: root
    password: lzl0502
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1/aoyama_auth?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull"
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: lzl0502
#    database: 0
  cloud:
    nacos:
      # 服务注册
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 82477b99-89cf-4a17-9164-97f65da64e8f
        group: ${spring.profiles.active}
  # 开启采集链路
  sleuth:
    web:
      enabled: true
    # 设置 1就是百分之百收集 设置0.1即10%概率收集链路数据
    sampler:
      probability: 1.0
    zipkin:
      base-url: "http://localhost:9411/"
      sender:
        type: web

feign:
  httpclient:
    enabled: true


#logging:
#  level:
#    root: debug
#    org:
#      springframework:
#        cloud:
#          gateway:
#            filter:
#              LoadBalancerClientFilter : info