server:
  port: 8086

spring:
  application:
    name: auth
  datasource:
    username: root
    password: lzl0502
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://121.5.162.245:3306/aoyama_auth?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull"
  redis:
    host: 121.5.162.245
    port: 6379
    database: 0
  cloud:
    nacos:
      # 服务注册
      discovery:
        server-addr: 121.5.162.245:8848
        namespace: 82477b99-89cf-4a17-9164-97f65da64e8f
        group: ${spring.profiles.active}
    alibaba:
      seata:
        tx-service-group: aoyama


  # 链路跟踪  服务器资源不够
#  sleuth:
#    web:
#      client:
#        enabled: true
#      enabled: true
#    # 设置 1就是百分之百收集 设置0.1即10%概率收集链路数据
#    sampler:
#      probability: 1.0
#    zipkin:
#      base-url: "http://121.5.162.245:9411/"
#      sender:
#        type: web

feign:
  httpclient:
    enabled: true


#配置分布式事务
seata:
  enabled: true
  application-id: ${spring.application.name}
  # 事务分组
  tx-service-group: aoyama
  #开启数据库代理
  enable-auto-data-source-proxy: true
  # 配置服务
  config:
    type: nacos
    nacos:
      group: SEATA_GROUP
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      namespace: ${spring.cloud.nacos.discovery.namespace}
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      namespace: ${spring.cloud.nacos.discovery.namespace}

#logging:
#  level:
#    root: debug
#    org:
#      springframework:
#        cloud:
#          gateway:
#            filter:
#              LoadBalancerClientFilter : info