server:
  port: 8086

spring:
  application:
    name: auth
  datasource:
    username: root
    password: lzl0502
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://121.5.162.245:3306/aoyama_auth?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull"
  redis:
    database: 0
    port: 6379
    host: 121.5.162.245
    password: lzl0502
    lettuce:
      pool:
        max-idle: 8
        min-idle: 5
        max-active: 10
        max-wait: 1000
    timeout: 1000
  cloud:
    nacos:
      # 服务注册
      discovery:
        server-addr: http://121.5.162.245:8848
        namespace: 82477b99-89cf-4a17-9164-97f65da64e8f
        group: ${spring.profiles.active}
  # 开启采集链路
  sleuth:
    web:
      enabled: true
    # 设置 1就是百分之百收集 设置0.1即10%概率收集链路数据
    sampler:
      probability: 1.0
    zipkin:
      base-url: "http://121.5.162.245:9411/"
      sender:
        type: web

feign:
  httpclient:
    enabled: true


#logging:
#  level:
#    root: debug
#    org:
#      springframework:
#        cloud:
#          gateway:
#            filter:
#              LoadBalancerClientFilter : info