server:
  port: 6666

spring:
  application:
    name: getway
  sleuth:
    web:
      client:
        enabled: true
      enabled: true
    # 设置 1就是百分之百收集 设置0.1即10%概率收集链路数据
    sampler:
      probability: 1.0
    zipkin:
      base-url: "http://localhost:9411/"
      sender:
        type: web
  datasource:
    hikari:
      url: "jdbc:mysql://127.0.0.1/?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull"
      username: root
      password: lzl0502
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  security:
    oauth2:
      client:
        client-Id: "GATEWAY"
        client-secret: "lzl"
  cloud:
    nacos:
      # 服务发现
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 82477b99-89cf-4a17-9164-97f65da64e8f
        group: ${spring.profiles.active}
    gateway:
      routes:
        - id: aoyama-user
          uri: "http://127.0.0.1:8085"
          predicates:
            - Path=/user/**

        - id: aoyama-auth
          uri: "http://127.0.0.1:8086"
          predicates:
            - Path=/auth/**
feign:
  httpclient:
    enabled: true

security:
  oauth2:
    client:
      client-id: app
      client-secret: app
      access-token-uri: "http://127.0.0.1:8086/oauth/token"
      scope:
        - all
      user-authorization-uri: "http://127.0.0.1:8086/oauth/authorize"


#logging:
#  level:
#    root: debug
#    org:
#      springframework:
#        cloud:
#          gateway:
#            filter:
#              LoadBalancerClientFilter : TRACE