server:
  port: 6666

spring:
  application:
    name: getway
  #链路追踪 服务器资源不够
  #  sleuth:
  #    web:
  #      client:
  #        enabled: true
  #      enabled: true
  #    # 设置 1就是百分之百收集 设置0.1即10%概率收集链路数据
  #    sampler:
  #      probability: 1.0
  #    zipkin:
  #      base-url: "http://121.5.162.245:9411/"
  #      sender:
  #        type: web
  redis:
    host: 121.5.162.245
    port: 6379
    database: 0
  cloud:
    nacos:
      # 服务发现
      discovery:
        server-addr: 121.5.162.245:8848
        namespace: 82477b99-89cf-4a17-9164-97f65da64e8f
        group: ${spring.profiles.active}
    gateway:
      routes:
        - id: aoyama-user
          uri: "http://127.0.0.1:8085"
          predicates:
            - Path=/user/**

        - id: aoyama-auth
          uri: "http://127.0.0.1:8086"
          predicates:
            - Path=/auth/**

        - id: aoyama_workflow
          uri: "http://127.0.0.1:7999"
          predicates:
            - Path=/workflow/**
feign:
  httpclient:
    enabled: true

security:
  oauth2:
    client:
      client-id: app
      client-secret: app
      access-token-uri: "http://127.0.0.1:8086/oauth/token"
      scope:
        - all
      user-authorization-uri: "http://127.0.0.1:8086/oauth/authorize"


#配置分布式事务
seata:
  enabled: true
  application-id: ${spring.application.name}
  # 事务分组
  tx-service-group: aoyama
  #开启数据库代理
  enable-auto-data-source-proxy: true
  # 配置服务
  config:
    type: nacos
    nacos:
      group: SEATA_GROUP
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      namespace: ${spring.cloud.nacos.discovery.namespace}
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      namespace: ${spring.cloud.nacos.discovery.namespace}

#logging:
#  level:
#    root: debug
#    org:
#      springframework:
#        cloud:
#          gateway:
#            filter:
#              LoadBalancerClientFilter : TRACE