server:
  port: 8085

spring:
  application:
    name: user
  sleuth:
    web:
      client:
        enabled: true
      enabled: true
    # 设置 1就是百分之百收集 设置0.1即10%概率收集链路数据
    sampler:
      probability: 1.0
    zipkin:
      base-url: "http://localhost:9411/"
      sender:
        type: web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 82477b99-89cf-4a17-9164-97f65da64e8f
        group: ${spring.profiles.active}
  datasource:
    username: root
    password: lzl0502
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1/aoyama_user?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull"

feign:
  httpclient:
    enabled: true

security:
  oauth2:
    client:
      client-id: app
      client-secret: app
      access-token-uri: "http://127.0.0.1:8086/oauth/token"
      user-authorization-uri: "http://127.0.0.1:8086/oauth/authorize"
    resource:
      jwt:
        #(如果使用JWT，可以获的公钥用于 token 的验签)
        key-uri: "http://127.0.0.1:8086/oauth/token_key"

#logging:
#  level:
#    root: debug
#    org:
#      springframework:
#        cloud:
#          gateway:
#            filter:
#              LoadBalancerClientFilter : debug