server:
  port: 8088

spring:
  application:
    name: apyama-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 82477b99-89cf-4a17-9164-97f65da64e8f
        group: ${spring.profiles.active}
  datasource:
    username: root
    password: lzl0502
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1/aoyama_user?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull"


security:
  oauth2:
    client:
      client-id: app
      client-secret: app
      access-token-uri: " http://127.0.0.1:8086/oauth/token"
      scope:
        - all


logging:
  level:
    root: debug
    org:
      springframework:
        cloud:
          gateway:
            filter:
              LoadBalancerClientFilter : debug