server:
  port: 7999

spring:
  application:
    name: workflow

  cloud:
    nacos:
      discovery:
        server-addr: 121.5.162.245:8848
        namespace: 82477b99-89cf-4a17-9164-97f65da64e8f
        group: ${spring.profiles.active}
  datasource:
    url:

feign:
  httpclient:
    enabled: true

security:
  oauth2:
    client:
      client-id: app
      client-secret: app
      access-token-uri: "http://127.0.0.1:8086/oauth/token"
      user-authorization-uri: "http://127.0.0.1:8086/oauth/authorize"
    resource:
      jwt:
        #(如果使用JWT，可以获的公钥用于 token 的验签)
        key-uri: "http://127.0.0.1:8086/oauth/token_key"

#配置分布式事务
seata:
  enabled: true
  application-id: ${spring.application.name}
  # 事务分组
  tx-service-group: aoyama
  #开启数据库代理
  enable-auto-data-source-proxy: true
  # 配置服务
  config:
    type: nacos
    nacos:
      group: SEATA_GROUP
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      namespace: ${spring.cloud.nacos.discovery.namespace}
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      namespace: ${spring.cloud.nacos.discovery.namespace}